In [9]:
import numpy as np
import random

In [37]:
#TODO Implementar método doolitle
def doolitle(matriz):
    pass

In [54]:
def choleski(matriz):
    if np.linalg.det(matriz) <=0:
        return 'Para el método de Cholesky, el determinante debe ser positivo y resultó ser ' + str(np.linalg.det(matriz))
    B=np.transpose(matriz)
    if not np.array_equal(matriz,B):
        return 'Para el método de Cholesky, la matriz debe ser simetrica'

    L = np.linalg.cholesky(matriz)
    U = np.transpose(L)

    #return str(A)+' = '+str(L)+' * '+str(U)
    print('Matriz Triangular Resultante')
    return str(L)

In [47]:
n = int(input('Introduce el tamaño de la matriz cuadrada '))
A = np.zeros([n,n])

Introduce el tamaño de la matriz cuadrada  3


In [50]:
fill = input('Desea rellenar la matriz de manera manual o aleatorio?').lower()
if fill == 'aleatorio':
    for i in range(n):
        for j in range(n):
            A[i,j] = random.randint(0,10)
else:
    for i in range(n):
        for j in range(n):
            A[i,j] = int(input('Elemento ('+str(i+1)+','+str(j+1)+') '))


Desea rellenar la matriz de manera manual o aleatorio? manual
Elemento (1,1)  5
Elemento (1,2)  1
Elemento (1,3)  3
Elemento (2,1)  1
Elemento (2,2)  8
Elemento (2,3)  2
Elemento (3,1)  3
Elemento (3,2)  2
Elemento (3,3)  5


In [51]:
print('Matriz Generada')
print(A)

Matriz Generada
[[5. 1. 3.]
 [1. 8. 2.]
 [3. 2. 5.]]


In [52]:
choice = input('Seleccione el método de descomposición Doolitle o Choleski').lower()

Seleccione el método de descomposición Doolitle o Choleski choleski


In [55]:
if choice == 'doolitle':
    doolitle(A)
else:
    print(choleski(A))

Matriz Triangular Resultante
[[2.23606798 0.         0.        ]
 [0.4472136  2.79284801 0.        ]
 [1.34164079 0.50128041 1.71718314]]
